spring.application.name=vitalNode

#Definicion de la base de datos de mongo
spring.mongodb.uri=mongodb://localhost:27017/vital_node

#Declaracion de las variables de entorno en archivo .evn
jwt.secret=${JWT.secret}
jwt.expiration.access=${JWT.expiration.access}
jwt.expiration.refresh=${JWT.expiration.refresh}
jwt.inactividad.minutos=${JWT.inactividad.minutos}

#Usado para el uso de @index en validaciones.
spring.data.mongodb.auto-index-creation=true